### ISSUE TITLE
Unable to get NPU from openvino in python

### ISSUE THREAD

**Issue by sr99622** [canonical/intel-npu-driver-snap#17]
I have been struggling with this for a few days now. I am running Ubuntu on an Intel Core Ultra i5 125H. If I install the drivers directly to bare metal, I am able to get both NPU and GPU. However, when I try to access either from inside a snap container there is nothing there. I have followed the directions very carefully and have run the tests. I installed intel-npu-driver --beta from the snap store and the command `sudo cat /sys/module/firmware_class/parameters/path` returns `/var/snap/intel-npu-driver/4`.  The command `sudo dmesg | grep intel_vpu` returns 

```
[    1.929953] intel_vpu 0000:00:0b.0: enabling device (0000 -> 0002)
[    1.949333] intel_vpu 0000:00:0b.0: [drm] Firmware: intel/vpu/vpu_37xx_v0.0.bin, version: 20250306*MTL_CLIENT_SILICON-release*1130*ci_tag_ud202512_vpu_rc_20250306_1130*5064b5debc3
[    1.949342] intel_vpu 0000:00:0b.0: [drm] Scheduler mode: OS
[    2.054273] [drm] Initialized intel_vpu 1.0.0 for 0000:00:0b.0 on minor 0
[    5.323316] intel_vpu 0000:00:0b.0: [drm] Firmware: intel/vpu/vpu_37xx_v0.0.bin, version: 20250306*MTL_CLIENT_SILICON-release*1130*ci_tag_ud202512_vpu_rc_20250306_1130*5064b5debc3
[    5.323323] intel_vpu 0000:00:0b.0: [drm] Scheduler mode: OS
[    5.419435] [drm] Initialized intel_vpu 1.0.0 for 0000:00:0b.0 on minor 0
```
If I run the `intel-npu-driver.npu-umd-test --config=basic.yaml`, most of the tests pass, but there is one failure

```
[ RUN      ] Device.GetZesEngineGetActivity
NPU_LOG: *ERROR* [os_interface_imp.cpp:83] Failed to open /sys/dev/char/../../devices/pci0000:00/0000:00:0b.0/accel/accel0/../../npu_busy_time_us, errno: 13 (Permission denied)
/root/parts/npu-driver/src/validation/umd-test/test_device.cpp:124: Failure
Expected equality of these values:
  zesEngineGetActivity(engineHandlers[0], &engineStats)
    Which is: ZE_RESULT_ERROR_UNINITIALIZED (0x78000001)
  ZE_RESULT_SUCCESS
    Which is: ZE_RESULT_SUCCESS (0x0)

[  FAILED  ] Device.GetZesEngineGetActivity (0 ms)
```

Along with a few stray messages such as

```
NPU_LOG: *ERROR* [eventpool.cpp:97] Invalid desc pointer
NPU_LOG: *ERROR* [eventpool.cpp:101] Invalid phEvent pointer
NPU_LOG: *ERROR* [eventpool.cpp:97] Invalid desc pointer
NPU_LOG: *ERROR* [eventpool.cpp:105] Invalid signal flags
NPU_LOG: *ERROR* [eventpool.cpp:109] Invalid wait flags
[       OK ] Event.CreateEventWithInvalidParameters (0 ms)
[ RUN      ] Event.AllocateEventTwiceExpectError
NPU_LOG: *ERROR* [eventpool.cpp:119] Event from index 0 is already in use
```
At one point, I got an error window with the message `Error opening directory /home/stephen/snap/intel-npu-driver/4: Permission denied`, but I'm not sure where that came from and I was unable to reproduce.

I build a minimal snapcraft.yaml to test, and it fails to find NPU

```
name: test-npu
base: core24
version: '1.0'
summary: test-npu
description: |
  test-npu

grade: stable
confinement: strict

plugs:
  intel-npu:
    interface: custom-device
    custom-device: intel-npu-device
  npu-libs:
    interface: content
    content: npu-libs-2404
    target: $SNAP/usr/lib/npu-libs-2404

environment:
  LD_LIBRARY_PATH: $SNAP/usr/lib/npu-libs-2404

apps:
  test-npu:
    command: bin/launch-test-npu
    plugs:
      - intel-npu
      - npu-libs

parts:
  test-npu:
    plugin: python
    source: .
    python-packages:
      - openvino
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cat << 'EOF' > $SNAPCRAFT_PART_INSTALL/test-npu.py
      import openvino
      print("python test message")
      print(openvino.Core().available_devices)
      EOF
      cat << 'EOF' > $SNAPCRAFT_PART_INSTALL/bin/launch-test-npu
      #!/bin/sh
      echo "THIS IS A TEST"
      python --version
      python $SNAP/test-npu.py
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/launch-test-npu
```

Any help you could provide would be greatly appreciated.

Best Regards,

Stephen

**Comment by sr99622** [comment]
Oh my goodness, thank you so much for rescuing me, I thought I had gone down the rabbit hole there for a minute. I have been able to get both the NPU and GPU working. Your suggestion about connecting the plug was correct. I'm new to snap so this was something I wasn't aware of. The sample-consumer app was a big help, it's quite impressive.

There was one thing I wanted to ask you about that I haven't had a chance to fully research. I noticed when checking the connections that gimp seemed to be automatically connected. I had it installed on my machine prior to doing all of this, so I wasn't sure if gimp did this on it's own or if installing the openvino toolkit was the trigger. It seems like there is some code in the openvino toolkit there to make the connections. The reason I ask was if there was something I could do along those same lines with my own app so that users wouldn't have to make the connections themselves when installing.

Best Regards,

Stephen

**Comment by frenchwr** [comment]
Glad to hear that did the trick!

Interface auto-connections is something that's defined on the Snap Store side, you can find more details here: https://snapcraft.io/docs/auto-connection-mechanism

There is actually [active discussion](https://forum.snapcraft.io/t/gimp-auto-connection-to-theme-snaps/47181/6) about making the libs from `openvino-toolkit-2404` and `intel-npu-driver` auto-connect, but for now you will need to manually connect to them from your snap.

**Comment by frenchwr** [comment]
No problem - thanks for reaching out!
